### PR TITLE
Logging errors v.0.0.2 :)

### PR DESCRIPTION
**Pull request by Radzio310**
Yeeeeah

### CODE REVIEW

**Comment by Szczepanoo** [comment]
image

**Comment by Radzio310** [comment]
image

**Comment by Szczepanoo** [comment]
image

**Comment by Szczepanoo** [comment]
Why 1 blank line ?~!?!?!?!?!?!?!?!!1!11/

**Comment by Radzio310** [comment]
image

**Comment by Szczepanoo** [comment]
image

**Pull request merged**
