### PR TITLE
unit tests

### PR DESCRIPTION
**Pull request by Szczepanoo**
image

### CODE REVIEW

**Comment by Radzio310** [comment]
WHY 2 BLANK LINES?!?!?

**Comment by Szczepanoo** [comment]
sori

**Comment by Szczepanoo** [comment]
improved :)

**Comment by Radzio310** [comment]
80!? 80!?
THIS IS RIDICULOUS

**Comment by Szczepanoo** [comment]
image

**Comment by Szczepanoo** [comment]
image

**Pull request merged**
